GLOBAL.setmetatable(env,{__index=function(a,b)return GLOBAL.rawget(GLOBAL,b)end})
TUNING.COLOSSEUM_LEVELS_LONGSWORD={
    [0]={
        ["name"]="太刀模式",
        ["id"]="longsword"
    },
    [1]={
        ["supply"]={
            [1]={
                ["prefab"]="wathgrithrhat",
                ["number"]=1
            }
        },
        ["enemys"]={
            [1]={
                ["prefab"]="spider_warrior",
                ["position"]={["x"]=6,["z"]=-10}
            },
            [2]={
                ["prefab"]="spider_warrior",
                ["position"]={["x"]=0,["z"]=-12}
            },
            [3]={
                ["prefab"]="spider_warrior",
                ["position"]={["x"]=-6,["z"]=-10}
            }
        }
    },
    [2]={
        ["supply"]={
        },
        ["enemys"]={
            [1]={
                ["prefab"]="spider_healer",
                ["position"]={["x"]=10,["z"]=-6}
            },
            [2]={
                ["prefab"]="spider_dropper",
                ["position"]={["x"]=6,["z"]=-10}
            },
            [3]={
                ["prefab"]="spider_dropper",
                ["position"]={["x"]=-6,["z"]=-10}
            },
            [4]={
                ["prefab"]="spider_healer",
                ["position"]={["x"]=-10,["z"]=-6}
            }
        }
    },
    [3]={
        ["supply"]={
            [1]={
                ["prefab"]="meat_dried",
                ["number"]=1
            }
        },
        ["enemys"]={
            [1]={
                ["prefab"]="tallbird",
                ["position"]={["x"]=6,["z"]=-10}
            },
            [2]={
                ["prefab"]="tallbird",
                ["position"]={["x"]=-6,["z"]=-10}
            }
        }
    },
    [4]={
        ["supply"]={
            [1]={
                ["prefab"]="wathgrithrhat",
                ["number"]=1
            }
        },
        ["enemys"]={
            [1]={
                ["prefab"]="pigguard",
                ["position"]={["x"]=6,["z"]=-10}
            },
            [2]={
                ["prefab"]="pigguard",
                ["position"]={["x"]=0,["z"]=-12}
            },
            [3]={
                ["prefab"]="pigguard",
                ["position"]={["x"]=-6,["z"]=-10}
            }
        }
    },
    [5]={
        ["supply"]={
            [1]={
                ["prefab"]="meat_dried",
                ["number"]=1
            }
        },
        ["enemys"]={
            [1]={
                ["prefab"]="icehound",
                ["position"]={["x"]=10,["z"]=-6}
            },
            [2]={
                ["prefab"]="icehound",
                ["position"]={["x"]=6,["z"]=-10}
            },
            [3]={
                ["prefab"]="icehound",
                ["position"]={["x"]=-6,["z"]=-10}
            },
            [4]={
                ["prefab"]="icehound",
                ["position"]={["x"]=-10,["z"]=-6}
            }
        }
    },
    [6]={
        ["supply"]={
        },
        ["enemys"]={
            [1]={
                ["prefab"]="firehound",
                ["position"]={["x"]=10,["z"]=-6}
            },
            [2]={
                ["prefab"]="firehound",
                ["position"]={["x"]=6,["z"]=-10}
            },
            [3]={
                ["prefab"]="firehound",
                ["position"]={["x"]=-6,["z"]=-10}
            },
            [4]={
                ["prefab"]="firehound",
                ["position"]={["x"]=-10,["z"]=-6}
            }
        }
    },
    [7]={
        ["supply"]={
            [1]={
                ["prefab"]="meat_dried",
                ["number"]=1
            }
        },
        ["enemys"]={
            [1]={
                ["prefab"]="spider_healer",
                ["position"]={["x"]=6,["z"]=-10}
            },
            [2]={
                ["prefab"]="spiderqueen",
                ["position"]={["x"]=0,["z"]=-12}
            },
            [3]={
                ["prefab"]="spider_healer",
                ["position"]={["x"]=-6,["z"]=-10}
            }
        }
    },
    [8]={
        ["supply"]={
            [1]={
                ["prefab"]="wathgrithrhat",
                ["number"]=1
            }
        },
        ["enemys"]={
            [1]={
                ["prefab"]="worm",
                ["position"]={["x"]=10,["z"]=-6}
            },
            [2]={
                ["prefab"]="worm",
                ["position"]={["x"]=6,["z"]=-10}
            },
            [3]={
                ["prefab"]="worm",
                ["position"]={["x"]=0,["z"]=-12}
            },
            [4]={
                ["prefab"]="worm",
                ["position"]={["x"]=-6,["z"]=-10}
            },
            [5]={
                ["prefab"]="worm",
                ["position"]={["x"]=-10,["z"]=-6}
            }
        }
    },
    [9]={
        ["supply"]={
            [1]={
                ["prefab"]="meat_dried",
                ["number"]=1
            }
        },
        ["enemys"]={
            [1]={
                ["prefab"]="leif",
                ["position"]={["x"]=6,["z"]=-10}
            },
            [2]={
                ["prefab"]="leif",
                ["position"]={["x"]=0,["z"]=-12}
            },
            [3]={
                ["prefab"]="leif",
                ["position"]={["x"]=-6,["z"]=-10}
            }
        }
    },
    [10]={
        ["supply"]={
        },
        ["enemys"]={
            [1]={
                ["prefab"]="krampus",
                ["position"]={["x"]=10,["z"]=-6}
            },
            [2]={
                ["prefab"]="krampus",
                ["position"]={["x"]=6,["z"]=-10}
            },
            [3]={
                ["prefab"]="krampus",
                ["position"]={["x"]=-6,["z"]=-10}
            },
            [4]={
                ["prefab"]="krampus",
                ["position"]={["x"]=-10,["z"]=-6}
            }
        }
    },
    [11]={
        ["supply"]={
            [1]={
                ["prefab"]="meat_dried",
                ["number"]=1
            }
        },
        ["enemys"]={
            [1]={
                ["prefab"]="firehound",
                ["position"]={["x"]=6,["z"]=-10}
            },
            [2]={
                ["prefab"]="warg",
                ["position"]={["x"]=0,["z"]=-12}
            },
            [3]={
                ["prefab"]="firehound",
                ["position"]={["x"]=-6,["z"]=-10}
            }
        }
    },
    [12]={
        ["supply"]={
            [1]={
                ["prefab"]="jellybean_spice_chili",
                ["number"]=1
            }
        },
        ["enemys"]={
            [1]={
                ["prefab"]="bishop",
                ["position"]={["x"]=10,["z"]=-6}
            },
            [2]={
                ["prefab"]="knight",
                ["position"]={["x"]=6,["z"]=-10}
            },
            [3]={
                ["prefab"]="knight",
                ["position"]={["x"]=0,["z"]=-12}
            },
            [4]={
                ["prefab"]="knight",
                ["position"]={["x"]=-6,["z"]=-10}
            },
            [5]={
                ["prefab"]="bishop",
                ["position"]={["x"]=-10,["z"]=-6}
            }
        }
    },
    [13]={
        ["supply"]={
            [1]={
                ["prefab"]="hivehat",
                ["number"]=1
            }
        },
        ["enemys"]={
            [1]={
                ["prefab"]="deerclops",
                ["position"]={["x"]=0,["z"]=-12}
            }
        }
    },
    [14]={
        ["supply"]={
            [1]={
                ["prefab"]="meat_dried",
                ["number"]=1
            }
        },
        ["enemys"]={
            [1]={
                ["prefab"]="moose",
                ["position"]={["x"]=0,["z"]=-12}
            }
        }
    },
    [15]={
        ["supply"]={
            [1]={
                ["prefab"]="meat_dried",
                ["number"]=1
            }
        },
        ["enemys"]={
            [1]={
                ["prefab"]="bearger",
                ["position"]={["x"]=0,["z"]=-12}
            }
        }
    },
    [16]={
        ["supply"]={
            [1]={
                ["prefab"]="jellybean_spice_chili",
                ["number"]=1
            },
            [2]={
                ["prefab"]="ruinshat",
                ["number"]=1
            },
            [3]={
                ["prefab"]="voltgoatjelly_spice_chili",
                ["number"]=1
            }
        },
        ["enemys"]={
            [1]={
                ["prefab"]="klaus",
                ["position"]={["x"]=0,["z"]=-12}
            }
        }
    },
    [17]={
        ["supply"]={
            [1]={
                ["prefab"]="ruinshat",
                ["number"]=1
            },
            [2]={
                ["prefab"]="voltgoatjelly_spice_chili",
                ["number"]=1
            }
        },
        ["enemys"]={
            [1]={
                ["prefab"]="minotaur",
                ["position"]={["x"]=0,["z"]=-12}
            }
        }
    },
    [18]={
        ["supply"]={
            [1]={
                ["prefab"]="jellybean_spice_chili",
                ["number"]=1
            },
            [2]={
                ["prefab"]="ruinshat",
                ["number"]=1
            },
            [3]={
                ["prefab"]="voltgoatjelly_spice_chili",
                ["number"]=1
            }
        },
        ["enemys"]={
            [1]={
                ["prefab"]="alterguardian_phase3",
                ["position"]={["x"]=0,["z"]=-12}
            }
        }
    }
}
local language = TUNING.COLOSSEUM_LANGUAGE
if not language then
    TUNING.COLOSSEUM_LEVELS_LONGSWORD[0].name="LongSword Mode"
end